language: python
dist: trusty
sudo: required

env:
  - VERSION=trusty
  - VERSION=xenial

before_install:
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq
install:
- pip install docker==2.7.0
- pip install ansible
- pip install ansible-container[docker]
script:
  # https://github.com/ansible/ansible-container/issues/802
- mkdir -p ~/.docker/ && touch ~/.docker/config.json
- echo '{}' > ~/.docker/config.json
- "make test-${VERSION}"
cache:
  directories:
    - $HOME/.cache/pip
notifications:
  email:
    recipients:
      - jasonheecs@gmail.com
    on_success: never
    on_failure: always