language: python
dist: trusty
sudo: required

before_install:
- sudo apt-add-repository 'deb http://archive.ubuntu.com/ubuntu trusty-backports universe'
- sudo apt-get update -qq
install:
- pip install docker==2.7.0
- pip install ansible
- pip install ansible-container[docker]
script:
- make test

notifications:
  email:
    recipients:
      - jasonheecs@gmail.com
    on_success: never
    on_failure: always