---
- name: Create auth log if it does not exist
  command: touch /var/log/auth.log
  args:
    creates: /var/log/auth.log
    warn: no

- name: Ensure fail2ban is installed
  apt:
    name: fail2ban
    state: latest
    update_cache: yes
  notify:
    - restart fail2ban

- name: Ensure fail2ban is configured
  template:
    src: "{{ item }}.j2"
    dest: /etc/fail2ban/{{ item }}
  with_items:
    - jail.local
    - fail2ban.local
  notify:
    - restart fail2ban

- name: Ensure fail2ban starts when machine is rebooted
  service:
    name: fail2ban
    state: started
    enabled: yes